import type { Step } from "onborda";

export const personalTourSteps: Step[] = [
  {
    icon: "👋",
    title: "Welcome to Tasks!",
    content: "Here's a quick tour to get you started. Everything you need is on one screen.",
    selector: "#onborda-header",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "✅",
    title: "Add a Task",
    content: "Click the Add button to open the task form. Type a title, pick a due date, then submit.",
    selector: "#onborda-add-task",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "📋",
    title: "Your Task List",
    content: "All your personal tasks live here. Click a task to see details, comments, and attachments. Mark tasks done when finished.",
    selector: "#onborda-task-list",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "🔔",
    title: "Notifications & More",
    content: "Check notifications, your momentum score, and switch themes from the top-right icons. When you're ready, head to the Dashboard for team features.",
    selector: "#onborda-header-actions",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
];

export const teamOwnerTourSteps: Step[] = [
  {
    icon: "👥",
    title: "Teams Dashboard",
    content: "This is your team workspace. All shared tasks, discussions, and files live here.",
    selector: "#onborda-dashboard-nav",
    side: "right",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "📊",
    title: "Teams",
    content: "Create teams, invite people, and assign shared work from one place.",
    selector: "#onborda-dashboard-dashboard-teams",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "📈",
    title: "Progress",
    content: "See open and finished work across your teams at a glance.",
    selector: "#onborda-dashboard-dashboard-analytics",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "⚙️",
    title: "Settings",
    content: "Turn optional team tools on only when the work needs them.",
    selector: "#onborda-dashboard-dashboard-features",
    side: "right",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "🎯",
    title: "You're All Set!",
    content: "Jump back to your personal tasks anytime, or explore your team's workspace.",
    selector: "#onborda-header",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
];

export const teamMemberTourSteps: Step[] = [
  {
    icon: "👥",
    title: "Teams Dashboard",
    content: "This is your team workspace. Shared tasks, discussions, and files are organized here.",
    selector: "#onborda-dashboard-nav",
    side: "right",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "📊",
    title: "Teams",
    content: "Open Teams to view people, assignments, and progress updates.",
    selector: "#onborda-dashboard-dashboard-teams",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "📈",
    title: "Track Team Progress",
    content: "Check Progress to understand open and finished work over time.",
    selector: "#onborda-dashboard-dashboard-analytics",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "🎯",
    title: "Done",
    content: "You are ready to work with your team tasks. Return to personal tasks anytime from the header.",
    selector: "#onborda-header",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
];

export const teamTourSteps: Step[] = [
  {
    icon: "👥",
    title: "Teams Workspace",
    content: "This area is for shared team workspaces. Use the left navigation to move across team features.",
    selector: "#onborda-dashboard-nav",
    side: "right",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "📊",
    title: "Teams",
    content: "View assigned work and progress. If you own a team, you can also create tasks and assign members here.",
    selector: "#onborda-dashboard-dashboard-teams",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "📈",
    title: "Progress",
    content: "Check open and finished work to understand delivery health.",
    selector: "#onborda-dashboard-dashboard-analytics",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "⚙️",
    title: "Team Settings",
    content: "Owners can tune optional tools like comments and attachments in Settings.",
    selector: "#onborda-dashboard-dashboard-features",
    side: "right",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
  {
    icon: "🎯",
    title: "You Are Ready",
    content: "Use personal tasks for your own workflow and dashboard sections for team collaboration.",
    selector: "#onborda-header",
    side: "bottom",
    showControls: false,
    pointerPadding: 8,
    pointerRadius: 10,
  },
];
