export type UseCase = {
  slug: string;
  audience: string;
  eyebrow: string;
  title: string;
  description: string;
  painPoints: string[];
  workflow: string[];
  scenarioTitle: string;
  scenario: string;
  features: string[];
  faq: Array<{ question: string; answer: string }>;
  cta: string;
  priority: "high" | "standard";
};

export const useCases: UseCase[] = [
  {
    slug: "simple-personal-todo-list",
    audience: "Personal users",
    eyebrow: "Personal to-do list",
    title: "A to-do list you do not have to learn.",
    description: "Tuduvia keeps personal tasks clear enough to open, read, finish, and move on. No boards, no setup ritual, no productivity ceremony.",
    painPoints: ["Too many to-do apps become projects before you add one task.", "Notes, chats, and memory make important things disappear.", "Busy people need the next action, not another system to maintain."],
    workflow: ["Add the thing you need to remember.", "Give it a due date or priority when it matters.", "Mark it done, or undo it if you tapped too fast."],
    scenarioTitle: "A normal week without the mental noise",
    scenario: "A personal user adds bills, errands, calls, appointments, and small work reminders into one calm Tuduvia list. In the morning they check what matters today. At night they clear completed items without sorting boards, labels, or views.",
    features: ["One clear personal task list", "Due dates and priority", "Simple completion and undo", "Fast daily review", "Works well on mobile"],
    faq: [
      { question: "Is Tuduvia too much for one person?", answer: "No. Tuduvia starts as a simple personal list. Team features stay out of the way until you invite someone." },
      { question: "Do I need to set up projects first?", answer: "No. You can create your first task immediately and organize later only if you need to." },
    ],
    cta: "Start with your first personal task.",
    priority: "high",
  },
  {
    slug: "personal-productivity-for-busy-people",
    audience: "Busy adults",
    eyebrow: "Busy life",
    title: "When your head is full, make the next task obvious.",
    description: "Use Tuduvia to keep daily work, home, errands, and follow-ups visible without turning your life into a dashboard.",
    painPoints: ["The day starts with too many loose thoughts.", "Small obligations hide in messages, notebooks, and memory.", "Complex productivity systems become another chore."],
    workflow: ["Drop tasks into one list as they appear.", "Pick what matters today.", "Finish, defer, or ask someone for help when a task becomes shared."],
    scenarioTitle: "A day that stays readable",
    scenario: "A busy person tracks a customer call, a school payment, a grocery stop, and a repair appointment in Tuduvia. They do not build a productivity method. They just keep the day visible and finish what they can.",
    features: ["Fast task capture", "Today-friendly task list", "Priority markers", "Mobile-friendly layout", "Optional team invites"],
    faq: [
      { question: "Can I use Tuduvia for work and personal tasks together?", answer: "Yes. Keep personal tasks simple, then create a team only when you need shared ownership." },
      { question: "Will Tuduvia push me into complex planning?", answer: "No. The product is designed around the shortest path from task to done." },
    ],
    cta: "Make today visible.",
    priority: "standard",
  },
  {
    slug: "school-project-task-list",
    audience: "Students",
    eyebrow: "School projects",
    title: "Run a school project without confusing your group.",
    description: "Turn assignments into clear tasks your classmates can understand, own, and finish before the deadline.",
    painPoints: ["Group project tasks get buried in chat.", "One student ends up reminding everyone again and again.", "Students need clarity, not project management training."],
    workflow: ["Create a temporary team for the project.", "Add research, slides, design, practice, and submission tasks.", "Assign each task to a classmate and track what is still open."],
    scenarioTitle: "A presentation that does not depend on memory",
    scenario: "Four students have a presentation due Friday. One creates a Tuduvia team, adds tasks for research, slide design, speaking notes, practice, and final upload, then assigns each person. The group chat stays for discussion while Tuduvia holds the work.",
    features: ["Temporary teams", "Assignment by person", "Due dates", "Comments for context", "Simple invite flow"],
    faq: [
      { question: "Can classmates understand it quickly?", answer: "Yes. Tuduvia keeps the workflow simple: task, owner, due date, done." },
      { question: "Can we use it for one project only?", answer: "Yes. Create a team for the assignment and stop using it when the project is finished." },
    ],
    cta: "Start a school project list.",
    priority: "high",
  },
  {
    slug: "home-family-task-list",
    audience: "Families and homes",
    eyebrow: "Home tasks",
    title: "One simple place for home tasks everyone keeps forgetting.",
    description: "Keep chores, repairs, shopping, appointments, and shared home responsibilities visible without running the house like an office.",
    painPoints: ["Home tasks vanish into memory and repeated reminders.", "People forget who agreed to do what.", "Family tools need to be simple enough for different ages and habits."],
    workflow: ["Add the home task once.", "Assign it to yourself or a family member.", "Use comments or files when details matter."],
    scenarioTitle: "A shared home list that stays human",
    scenario: "A family uses Tuduvia for grocery items, bill dates, appliance repair, school forms, and weekend chores. Everyone sees what is open and marks their part done from a phone.",
    features: ["Shared home team", "Personal and assigned tasks", "Due dates", "Mobile-friendly task completion", "Undo for mistakes"],
    faq: [
      { question: "Is this too formal for family use?", answer: "No. Tuduvia is lighter than a board and clearer than a chat thread." },
      { question: "Can one person manage the list for everyone?", answer: "Yes. A team leader can add tasks and assign them to the right people." },
    ],
    cta: "Create your home task list.",
    priority: "high",
  },
  {
    slug: "senior-friendly-todo-list",
    audience: "Senior citizens",
    eyebrow: "Senior friendly",
    title: "Simple enough to read, tap, and finish.",
    description: "Tuduvia gives older users and simplicity-loving people a readable task list without confusing boards, panels, and setup screens.",
    painPoints: ["Many apps hide simple tasks behind too many controls.", "Important reminders need to be readable on a phone.", "Family help should not require learning a project tool."],
    workflow: ["Add appointments, calls, bills, or refill tasks.", "Open the list to see what is next.", "Invite a family member when help is needed."],
    scenarioTitle: "A clear list for everyday reminders",
    scenario: "A retired user keeps medicine refills, bill dates, doctor appointments, and family calls in Tuduvia. A family member can help add or track tasks when needed, without teaching a complicated tool.",
    features: ["Readable task list", "Simple completion", "Family collaboration", "Due dates", "No board setup"],
    faq: [
      { question: "Is Tuduvia designed only for technical users?", answer: "No. It is built for people who want a simple list and clear ownership." },
      { question: "Can a family member help manage tasks?", answer: "Yes. Invite them to a team when shared help is useful." },
    ],
    cta: "Try the simple list.",
    priority: "standard",
  },
  {
    slug: "gen-z-simple-task-app",
    audience: "Younger users",
    eyebrow: "Clean daily tasks",
    title: "Fast, clean, and not another life-management dashboard.",
    description: "Tuduvia helps students, creators, and younger users keep life moving without a heavy productivity identity.",
    painPoints: ["Many apps feel like homework before the real homework starts.", "Ideas, plans, and reminders scatter across chat and notes.", "Young users want speed, clean UI, and mobile comfort."],
    workflow: ["Add tasks for study, work, content, or plans.", "Group people only when a task becomes shared.", "Finish quickly from phone or desktop."],
    scenarioTitle: "A simple list for a fast week",
    scenario: "A Gen Z user tracks study tasks, a side hustle idea, gym reminders, and a weekend plan with friends. When the plan needs help, they create a temporary team and assign what each friend should handle.",
    features: ["Fast mobile use", "Temporary teams", "Priority", "Simple sign up"],
    faq: [
      { question: "Is Tuduvia only for business teams?", answer: "No. It is just as useful for personal lists, school work, side projects, and friend plans." },
      { question: "Does it force a method?", answer: "No. Tuduvia keeps the method simple: write, assign if needed, finish." },
    ],
    cta: "Make your week easier.",
    priority: "standard",
  },
  {
    slug: "neighborhood-task-management",
    audience: "Neighborhood groups",
    eyebrow: "Neighbors",
    title: "Organize neighbors without creating a committee headache.",
    description: "Plan local cleanups, shared repairs, apartment tasks, and community efforts with clear owners and no training.",
    painPoints: ["Neighborhood work often starts in chat and disappears there.", "Volunteers need specific jobs, not long instructions.", "Temporary projects should not require a permanent tool."],
    workflow: ["Create a temporary neighborhood team.", "Add tasks for supplies, calls, locations, and reminders.", "Assign people and close the project when it is done."],
    scenarioTitle: "A cleanup day that stays organized",
    scenario: "A neighbor creates a Tuduvia team for a cleanup day, then adds tasks for poster printing, supply pickup, volunteer reminders, and cleanup zones. Everyone gets a clear task instead of scanning a long chat thread.",
    features: ["Temporary teams", "Assignments", "Due dates", "Comments", "Mobile completion"],
    faq: [
      { question: "Can non-technical neighbors join?", answer: "Yes. They only need to see their tasks and mark them done." },
      { question: "Can we stop using the team after the event?", answer: "Yes. Tuduvia works well for short-lived groups." },
    ],
    cta: "Organize your local project.",
    priority: "standard",
  },
  {
    slug: "friends-trip-planning-tasks",
    audience: "Friend groups",
    eyebrow: "Trips and plans",
    title: "Plan a trip without losing tasks in chat.",
    description: "Use Tuduvia for the things your friend group actually needs to do: tickets, stays, transport, food, packing, and payments.",
    painPoints: ["Chat is great for talking, bad for remembering.", "One person becomes the unpaid reminder machine.", "Small plans become stressful when nobody owns the details."],
    workflow: ["Create a trip team.", "Add tasks for bookings, money, transport, and packing.", "Assign friends and keep the open list visible."],
    scenarioTitle: "A weekend trip with fewer reminders",
    scenario: "A friend group planning a weekend trip uses Tuduvia for hotel booking, ticket purchase, snack list, driver schedule, and payment reminders. The chat stays fun while the tasks stay clear.",
    features: ["Shared task list", "Clear owners", "Comments", "Due dates", "Mobile-first usage"],
    faq: [
      { question: "Is Tuduvia too serious for friend plans?", answer: "No. It is simple enough for temporary plans and practical enough to prevent forgotten tasks." },
      { question: "Can we use it only for one trip?", answer: "Yes. Create the team, finish the trip tasks, and move on." },
    ],
    cta: "Plan the next trip clearly.",
    priority: "standard",
  },
  {
    slug: "small-business-task-management",
    audience: "Small business owners",
    eyebrow: "Small business",
    title: "Small business tasks without project-management complexity.",
    description: "Tuduvia helps owners and operators assign daily work, customer follow-ups, supplier calls, and admin tasks without training the team on boards.",
    painPoints: ["Small businesses need execution more than complex planning.", "Owners lose time asking who finished what.", "Staff may avoid tools that look technical."],
    workflow: ["Create your business team.", "Add daily tasks and assign the responsible person.", "Use notifications and completion to see what is still open."],
    scenarioTitle: "A business day with clear ownership",
    scenario: "A shop owner tracks customer callbacks, invoice checks, supplier follow-ups, cleaning tasks, and stock reminders in Tuduvia. Staff only need to open their list and finish assigned work.",
    features: ["Team task assignment", "Member task visibility", "Notifications", "Comments and files", "Admin controls"],
    faq: [
      { question: "Can non-IT staff use Tuduvia?", answer: "Yes. The workflow is intentionally plain: task, owner, due date, done." },
      { question: "Does Tuduvia replace complex project tools?", answer: "For many small businesses, yes. If the real need is clear task ownership, Tuduvia is lighter." },
    ],
    cta: "Start your business task list.",
    priority: "high",
  },
  {
    slug: "non-it-team-task-management",
    audience: "Non-IT teams",
    eyebrow: "Non-technical teams",
    title: "Task management for teams that do not speak software.",
    description: "Give retail, service, admin, field, and local teams one simple place to see assigned work and mark it done.",
    painPoints: ["Many tools assume every team wants boards, fields, automations, and workflows.", "Non-technical users need clarity before customization.", "Managers need a tool people will actually open."],
    workflow: ["Owner adds tasks in plain language.", "Team members see their assigned work.", "Everyone completes tasks from a simple list."],
    scenarioTitle: "A team that understands the tool on day one",
    scenario: "A service team lead uses Tuduvia to assign customer follow-ups, stock checks, and closing tasks. Team members do not learn a methodology. They just read their tasks and finish them.",
    features: ["Simple team invitations", "Assigned tasks", "Mobile-friendly UI", "Comments", "Realtime updates"],
    faq: [
      { question: "Do team members need training?", answer: "No. Tuduvia is designed so a team can start with a short explanation: open your list and finish your assigned tasks." },
      { question: "Can managers still see progress?", answer: "Yes. Team owners can see open work and keep responsibilities visible." },
    ],
    cta: "Give your team a list they can use.",
    priority: "high",
  },
  {
    slug: "team-leader-task-tracker",
    audience: "Team leaders",
    eyebrow: "Team leads",
    title: "Lead the work without chasing every person.",
    description: "Tuduvia makes ownership visible so supervisors and coordinators can spend less time asking for updates.",
    painPoints: ["Leaders repeat the same reminders across chat and calls.", "Tasks are open, but nobody knows who owns them.", "Small teams need accountability without heavy reporting."],
    workflow: ["Create tasks with an owner.", "Add deadlines and context.", "Check the list instead of chasing every person."],
    scenarioTitle: "A shift lead with a visible plan",
    scenario: "A supervisor adds morning setup, customer callbacks, stock checks, and end-of-day close tasks to Tuduvia. Each task has an owner, so the lead can see progress without interrupting everyone.",
    features: ["Owner assignment", "Member task view", "Notifications", "Priority", "Completion history via app flow"],
    faq: [
      { question: "Will this slow my team down?", answer: "No. Tuduvia is intentionally lighter than a board and faster than repeated follow-ups." },
      { question: "Can I manage temporary helpers?", answer: "Yes. Invite people when needed and assign only the tasks that concern them." },
    ],
    cta: "Make ownership visible.",
    priority: "standard",
  },
  {
    slug: "admin-office-task-list",
    audience: "Office and admin teams",
    eyebrow: "Office follow-ups",
    title: "Turn office follow-ups into finished tasks.",
    description: "Keep documents, approvals, renewals, calls, and meeting preparation in a shared list that stays easy to scan.",
    painPoints: ["Office work has many small handoffs.", "Email and chat are hard to audit quickly.", "Admin teams need fewer loose ends and clearer next actions."],
    workflow: ["Add each follow-up as a task.", "Attach notes or files when needed.", "Assign the person responsible and track completion."],
    scenarioTitle: "An office list that catches loose ends",
    scenario: "An office manager uses Tuduvia for document collection, appointment confirmations, renewal dates, customer callbacks, and meeting prep. Tasks stop living only in someone else's inbox.",
    features: ["Shared task list", "Files", "Comments", "Due dates", "Notifications"],
    faq: [
      { question: "Can Tuduvia replace spreadsheets for follow-ups?", answer: "For simple task ownership, yes. Tuduvia is easier for daily action than a spreadsheet row." },
      { question: "Can we add details to a task?", answer: "Yes. Use notes, comments, and attachments when context matters." },
    ],
    cta: "Clear the office follow-up list.",
    priority: "standard",
  },
  {
    slug: "clinic-service-team-tasks",
    audience: "Service teams",
    eyebrow: "Busy service days",
    title: "Simple task tracking for service teams with busy days.",
    description: "Use Tuduvia for operational tasks like supplies, callbacks, room prep, maintenance, and daily handoffs without making compliance claims.",
    painPoints: ["Service teams move quickly and forget small operational tasks.", "Tasks get passed verbally and disappear.", "The best tool is the one staff can understand immediately."],
    workflow: ["Add operational tasks in plain language.", "Assign owners for each shift or role.", "Use due dates and completion to keep the day moving."],
    scenarioTitle: "A calmer operations checklist",
    scenario: "A service team tracks supply checks, customer callbacks, setup work, repair follow-ups, and closing tasks in Tuduvia. Everyone sees their part without opening a complex project board.",
    features: ["Mobile-friendly tasks", "Assignments", "Priority", "Notifications", "Comments"],
    faq: [
      { question: "Is this for regulated records?", answer: "Tuduvia is for general task tracking. Do not use it as a replacement for regulated record systems unless reviewed for that use." },
      { question: "Can a busy team use it quickly?", answer: "Yes. The interface focuses on clear task lists and completion." },
    ],
    cta: "Make daily tasks visible.",
    priority: "standard",
  },
  {
    slug: "local-shop-task-management",
    audience: "Local shops",
    eyebrow: "Shop teams",
    title: "A task list your shop team can actually use.",
    description: "Track opening routines, customer orders, stock checks, supplier calls, and cleaning tasks without asking staff to learn project software.",
    painPoints: ["Shop work is practical and fast-moving.", "Tasks often sit on paper, memory, or chat.", "A complicated system will not survive a busy day."],
    workflow: ["Create a shop team.", "Add daily work and assign it to staff.", "Complete tasks from the phone as work gets done."],
    scenarioTitle: "A shop day with fewer missed details",
    scenario: "A local shop uses Tuduvia for opening checks, stock updates, supplier calls, customer pickup reminders, and end-of-day cleaning. Staff see only the work they need to finish.",
    features: ["Daily team list", "Assignments", "Priority", "Mobile completion", "Realtime refresh"],
    faq: [
      { question: "Can staff use Tuduvia from phones?", answer: "Yes. Tuduvia is designed to work cleanly on mobile browsers." },
      { question: "Do we need a setup meeting?", answer: "No. Start with one team and a few tasks." },
    ],
    cta: "Run today from one list.",
    priority: "standard",
  },
  {
    slug: "freelancer-client-task-list",
    audience: "Freelancers",
    eyebrow: "Client work",
    title: "Keep client work clear without a big project tool.",
    description: "Freelancers can track requests, revisions, files, deadlines, and delivery steps without building a heavy client portal.",
    painPoints: ["Client requests arrive across email, chat, and calls.", "Small revisions are easy to forget.", "Freelancers need to look organized without managing a complex system."],
    workflow: ["Add each client request as a task.", "Attach notes or files when useful.", "Invite collaborators only when the work becomes shared."],
    scenarioTitle: "A client project that stays lightweight",
    scenario: "A freelancer tracks logo revisions, copy changes, final file exports, and invoice reminders in Tuduvia. When a designer helps, they join only for the tasks they need to finish.",
    features: ["Task notes", "Files", "Due dates", "Temporary collaboration", "Personal task list"],
    faq: [
      { question: "Can I use Tuduvia without inviting clients?", answer: "Yes. Many freelancers can use it privately as their own execution list." },
      { question: "Can I invite a helper?", answer: "Yes. Invite someone when a task becomes shared work." },
    ],
    cta: "Organize client work simply.",
    priority: "standard",
  },
  {
    slug: "creator-content-task-list",
    audience: "Creators",
    eyebrow: "Content tasks",
    title: "Turn content ideas into tasks you actually finish.",
    description: "Keep ideas, scripts, filming, editing, posting, and follow-up tasks moving without a complicated content board.",
    painPoints: ["Ideas are easy; finishing the small steps is harder.", "Content work jumps between phone notes, chats, and files.", "Creators need a simple execution list, not a heavy workflow."],
    workflow: ["Add ideas as tasks.", "Break production into simple next actions.", "Invite helpers for editing, posting, or review when needed."],
    scenarioTitle: "A content week that gets finished",
    scenario: "A creator adds tasks for topic ideas, script notes, filming, thumbnail work, editing, captions, and posting. Tuduvia keeps the next action visible without forcing a board pipeline.",
    features: ["Personal ideas list", "Due dates", "Files", "Temporary helpers", "Simple completion"],
    faq: [
      { question: "Is Tuduvia a content calendar?", answer: "It is a simple task list. Use it when the main need is getting content steps done." },
      { question: "Can a small content team use it?", answer: "Yes. Invite team members and assign tasks when production becomes collaborative." },
    ],
    cta: "Finish the next content task.",
    priority: "standard",
  },
  {
    slug: "event-planning-task-list",
    audience: "Event organizers",
    eyebrow: "Small events",
    title: "Plan a small event without losing the small things.",
    description: "Use Tuduvia for birthdays, workshops, meetups, school events, and local gatherings where every small task matters.",
    painPoints: ["Events create many small tasks with one deadline.", "Helpers forget what they promised to handle.", "Chat gets noisy close to event day."],
    workflow: ["Create a temporary event team.", "Add venue, food, invites, transport, setup, and cleanup tasks.", "Assign helpers and watch the open list shrink."],
    scenarioTitle: "A small event with clear helpers",
    scenario: "An organizer uses Tuduvia for a workshop: venue confirmation, speaker reminders, chair setup, food order, check-in table, and cleanup. Each helper has a clear task before event day.",
    features: ["Temporary team", "Due dates", "Assignments", "Comments", "Final checklist"],
    faq: [
      { question: "Can Tuduvia handle one-time events?", answer: "Yes. It is especially useful when a short project needs temporary helpers." },
      { question: "Can helpers use it without training?", answer: "Yes. They only need to see and complete assigned tasks." },
    ],
    cta: "Plan the event clearly.",
    priority: "standard",
  },
  {
    slug: "volunteer-group-task-management",
    audience: "Volunteer groups",
    eyebrow: "Volunteer work",
    title: "Give volunteers clear tasks without software training.",
    description: "Coordinate charity, club, community, and local group work with simple assignments and visible progress.",
    painPoints: ["Volunteers need clarity quickly.", "Organizers cannot assume everyone uses the same tools.", "Tasks should be easy to understand and easy to finish."],
    workflow: ["Create a volunteer team for the effort.", "Add tasks with owners and due dates.", "Use comments for updates and finish the list together."],
    scenarioTitle: "A donation drive with visible work",
    scenario: "A volunteer group uses Tuduvia for pickup calls, poster printing, supply lists, driver assignments, and thank-you follow-ups. Everyone knows their part without a training session.",
    features: ["Simple invites", "Assigned tasks", "Due dates", "Comments", "Mobile access"],
    faq: [
      { question: "Can volunteers join for one project?", answer: "Yes. Tuduvia works well for temporary teams and one-time efforts." },
      { question: "Is it free to start?", answer: "Yes. Tuduvia is free to use now while we grow the user base." },
    ],
    cta: "Coordinate the next effort.",
    priority: "standard",
  },
  {
    slug: "simple-project-management-alternative",
    audience: "Board-fatigued teams",
    eyebrow: "Project management alternative",
    title: "When project management is too much, use a task list your team understands.",
    description: "Tuduvia is for people who need clear ownership and completion, not another board full of columns nobody updates.",
    painPoints: ["Boards can become more work than the work itself.", "Small teams rarely need a 57-click setup process.", "People avoid tools that make them feel behind before they begin."],
    workflow: ["Write the tasks.", "Assign the owners.", "Finish the work without managing a board."],
    scenarioTitle: "A small launch without a board",
    scenario: "A team preparing a small launch adds tasks for copy, setup, customer messages, file checks, and final review. They track ownership and completion in Tuduvia instead of moving cards across columns.",
    features: ["No boards", "Clear ownership", "Due dates", "Comments and files", "Notifications"],
    faq: [
      { question: "Is Tuduvia against project management?", answer: "No. Tuduvia is for work that needs a simpler path than traditional project management software." },
      { question: "Can we still collaborate?", answer: "Yes. Teams can assign tasks, comment, attach files, and track completion." },
    ],
    cta: "Try the simpler alternative.",
    priority: "standard",
  },
  {
    slug: "temporary-team-task-management",
    audience: "Temporary teams",
    eyebrow: "Temporary teams",
    title: "Create a temporary team, finish the work, move on.",
    description: "Use Tuduvia for short projects with school, home, neighbors, friends, business, clubs, or one-time helpers.",
    painPoints: ["Temporary groups do not want permanent software.", "The leader needs clarity without becoming a project manager.", "People need tasks they can understand instantly."],
    workflow: ["Create a team for the short project.", "Invite only the people involved.", "Assign tasks, finish the list, and move on."],
    scenarioTitle: "One short project, one clear list",
    scenario: "A person organizing a home repair weekend invites family and neighbors to a temporary Tuduvia team. Tasks for buying materials, calling the worker, clearing the area, and checking payment are assigned and completed before the weekend ends.",
    features: ["Temporary team setup", "Invites", "Assignments", "Realtime updates", "Completion and undo"],
    faq: [
      { question: "Can Tuduvia be used for short projects?", answer: "Yes. Temporary collaboration is one of Tuduvia's strongest fits." },
      { question: "Do people need to understand project management?", answer: "No. They only need to understand their task list." },
    ],
    cta: "Start a temporary team.",
    priority: "high",
  },
];

export function getUseCase(slug: string) {
  return useCases.find((useCase) => useCase.slug === slug);
}

export const highPriorityUseCases = useCases.filter((useCase) => useCase.priority === "high");
